### ISSUE TITLE
Travis still uses LifeMushroom Directory.

### ISSUE THREAD

**Issue by maorninja** [Apexton/Modular-Node.js-IRC-Bot#51]
As a result, it can't find the repo and still says "passing"

**Comment by maorninja** [comment]
@LifeMushroom @AlphaT3ch 

Um, are you guys going to fix this? Or are you just going to remove it altogether?

**Comment by LifeMushroom** [comment]
I don't really work on this repo anymore. If you want, open a pull request so I can merge it quickly.

**Comment by maorninja** [comment]
https://s3.amazonaws.com/archive.travis-ci.org/jobs/222629109/log.txt

This is the Log of the Travis commit that I just did...
